server:
  port: 8090

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  config:
   import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/user/**
        - id: DepartmentService
          uri: lb://DepartmentService
          predicates:
            - Path=/dept/**
